apiVersion: v1
kind: Pod
metadata:
 name: myapp-pod
 labels:
  app: myapp
  type: frontend
spec:
 containers:
  - name: nginx-controller
    image: nginx    
 tolerations:
  - key: app
    operator: equals
    value: blue
    effect: Noschedule
    
