apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2021-08-06T04:58:14Z"
  labels:
    name: mysql
  name: mysql
  namespace: default
  resourceVersion: "884"
  uid: dcd689d9-439b-494c-9297-9739ce7f2992
spec:
  containers:
  envFrom:
   - SecretRef:  
      name: db-secret
